version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: maildev/maildev
    volumes:
      - /home/maildev:/home/maildev:rw
    environment:
      - MAILDEV_MAIL_DIRECTORY=/home/maildev
    networks:
      - default
    ports: [1025, 1080]
###< symfony/mailer ###
