controllers:
    resource: ../src/Controller/
    type: attribute
app_logout:
    path: /logout
    methods: GET
rule:
    path: /pyramid/rule
    controller: App\Controller\PyramidController::rule
pyramid:
    path: /pyramid
    controller: App\Controller\PyramidController\